# Generated by Django 4.0.4 on 2022-06-06 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'ordering': ['-create', '-update']},
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 6, 17, 3, 32, 326977, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
