# Generated by Django 4.0.4 on 2022-06-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customerinfo_options_customerinfo_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'ordering': ['update', 'create']},
        ),
    ]
