# Generated by Django 4.0.4 on 2022-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_image_options_image_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='products/no-image.jpg', upload_to='products/%y/%m/%d'),
        ),
    ]
